### ISSUE TITLE
Generation of camera trajectories is not working (kaleido issue)

### ISSUE THREAD

**Issue by alessandro893** [imlixinyang/Director3D#7]
Camera trajectories not generating in Gradio. Strange issue cause by kaleido > 0.1.

To fix this issue install  kaleido-0.1.0.post1:
pip install kaleido==0.1.0post1

**Comment by imlixinyang** [comment]
Thank you! I will fix this issue in our README.

**Comment by Hanjiangli** [comment]
However, following the steps in this readme, this problem will occur: ERROR: No matching distribution found for kaleido==0.1.0.post1

**Comment by Hanjiangli** [comment]
The detail is "ERROR: Ignored the following versions that require a different python version: 1.14.0 Requires-Python >=3.10; 1.14.0rc1 Requires-Python >=3.10; 1.14.0rc2 Requires-Python >=3.10; 3.10.0.0 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <3.5; 3.7.4.2 Requires-Python >=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, <3.5
ERROR: Could not find a version that satisfies the requirement kaleido==0.1.0.post1 (from versions: 0.0.1rc3, 0.0.1rc4, 0.0.1rc5, 0.0.1rc6, 0.0.1rc8, 0.0.1rc9, 0.0.1, 0.0.2, 0.0.3, 0.0.3.post1, 0.1.0a2, 0.1.0a3, 0.1.0, 0.2.0rc1, 0.2.0, 0.2.1)"

**Comment by imlixinyang** [comment]
@Hanjiangli Have you tried directly run ``pip install kaleido``?

**Comment by Hanjiangli** [comment]
> @Hanjiangli Have you tried directly run `pip install kaleido`?

yes, it will install kaleido-0.2.1.

**Comment by Clear-3d** [comment]
> > @Hanjiangli Have you tried directly run `pip install kaleido`?
> 
> yes, it will install kaleido-0.2.1.

Hi,  kaleido-0.2.1 works fine for me, have you tried it?

**Comment by Hanjiangli** [comment]
> > > @Hanjiangli Have you tried directly run `pip install kaleido`?
> > 
> > 
> > yes, it will install kaleido-0.2.1.
> 
> Hi, kaleido-0.2.1 works fine for me, have you tried it?

I met some problems while running "python inference.py --export_all --text "a delicious hamburger on a wooden table." --num_refine_steps 0 --num_samples 4" 
Here are the details:
Traceback (most recent call last):
  File "/home/jst/code/Director3D-main/inference.py", line 4, in <module>
    from system_gm_ldm import GMLDMSystem
  File "/home/jst/code/Director3D-main/system_gm_ldm.py", line 6, in <module>
    from gm_ldm import GaussianDrivenLDM
  File "/home/jst/code/Director3D-main/gm_ldm.py", line 7, in <module>
    from modules.renderers.gaussians_renderer import GaussianRenderer, GaussianConverter
  File "/home/jst/code/Director3D-main/modules/renderers/gaussians_renderer.py", line 8, in <module>
    from diff_gaussian_rasterization import GaussianRasterizationSettings, GaussianRasterizer
  File "/home/jst/anaconda3/envs/d3d/lib/python3.9/site-packages/diff_gaussian_rasterization/__init__.py", line 15, in <module>
    from . import _C
ImportError: /home/jst/anaconda3/envs/d3d/lib/python3.9/site-packages/diff_gaussian_rasterization/_C.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZNSt15__exception_ptr13exception_ptr9_M_addrefEv

**Comment by imlixinyang** [comment]
@Hanjiangli Maybe you can try reinstalling ``diff-gaussian-rasterization`` by running:

```
pip uninstall diff-gaussian-rasterization 
pip install "git+https://github.com/ashawkey/diff-gaussian-rasterization.git"
```

You can also refer to a similar issue [here](https://github.com/graphdeco-inria/gaussian-splatting/issues/865#issuecomment-2223470419).

**Comment by Hanjiangli** [comment]
> @Hanjiangli Maybe you can try reinstalling `diff-gaussian-rasterization` by running:
> 
> ```
> pip uninstall diff-gaussian-rasterization 
> pip install "git+https://github.com/ashawkey/diff-gaussian-rasterization.git"
> ```
> 
> You can also refer to a similar issue [here](https://github.com/graphdeco-inria/gaussian-splatting/issues/865#issuecomment-2223470419).

I reinstalled it according to your method and still had the same problem. It may be that the versions do not match(my CUDA version is 12.2, torch-2.3.1)
