### ISSUE TITLE
How to install !!!

### ISSUE THREAD

**Issue by Yaoyaolingbro** [imlixinyang/Director3D#9]
I've try a lot but have no idea how to solve the bug!

```
(director3d) dzz@10-76-1-23:~/nas-dzz/Director3D$ pip install "git+https://github.com/ashawkey/diff-gaussian-rasterization.git"
Collecting git+https://github.com/ashawkey/diff-gaussian-rasterization.git
  Cloning https://github.com/ashawkey/diff-gaussian-rasterization.git to /tmp/pip-req-build-b8haqaa3
  Running command git clone --filter=blob:none --quiet https://github.com/ashawkey/diff-gaussian-rasterization.git /tmp/pip-req-build-b8haqaa3
  Resolved https://github.com/ashawkey/diff-gaussian-rasterization.git to commit 8829d14f814fccdaf840b7b0f3021a616583c0a1
  Running command git submodule update --init --recursive -q
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: diff_gaussian_rasterization
  Building wheel for diff_gaussian_rasterization (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [55 lines of output]
      No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
      running bdist_wheel
      /home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/torch/utils/cpp_extension.py:476: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
        warnings.warn(msg.format('we could not find ninja.'))
      running build
      running build_py
      creating build/lib.linux-x86_64-cpython-39/diff_gaussian_rasterization
      copying diff_gaussian_rasterization/__init__.py -> build/lib.linux-x86_64-cpython-39/diff_gaussian_rasterization
      running build_ext
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-b8haqaa3/setup.py", line 17, in <module>
          setup(
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/__init__.py", line 117, in setup
          return distutils.core.setup(**attrs)
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 183, in setup
          return run_commands(dist)
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 199, in run_commands
          dist.run_commands()
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/command/bdist_wheel.py", line 398, in run
          self.run_command("build")
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/dist.py", line 950, in run_command
          super().run_command(command)
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_command
          cmd_obj.run()
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 98, in run
          _build_ext.run(self)
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 499, in build_extensions
          _check_cuda_version(compiler_name, compiler_version)
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 383, in _check_cuda_version
          torch_cuda_version = packaging.version.parse(torch.version.cuda)
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/_vendor/packaging/version.py", line 56, in parse
          return Version(version)
        File "/home/dzz/miniconda3/envs/director3d/lib/python3.9/site-packages/setuptools/_vendor/packaging/version.py", line 200, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for diff_gaussian_rasterization
  Running setup.py clean for diff_gaussian_rasterization
Failed to build diff_gaussian_rasterization
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (diff_gaussian_rasterization)
```

**Comment by euminds** [comment]
I've got this bug too.

**Comment by imlixinyang** [comment]
Hi! @euminds and @Yaoyaolingbro .
This issue is raised when installing diff-gaussian-rasterization. So you may refer to [this related issue](https://github.com/ashawkey/diff-gaussian-rasterization/issues/8) and other issues in [ashawkey/diff-gaussian-rasterization](https://github.com/ashawkey/diff-gaussian-rasterization) and  [graphdeco-inria/diff-gaussian-rasterization](https://github.com/graphdeco-inria/diff-gaussian-rasterization).
